services:
  - type: web
    name: telegram-welcome-bot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python bot.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11

      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_ID
        sync: false

      - key: LINKS_CHANNEL
        sync: false
